---
title: 异常的详解
description: ' '
tags:
  - Java
  - 笔记
categories: Java
copyright: true
abbrlink: 7792860f
---



### 异常机制

#### Exception

#### 什么是异常

- ##### 实际工作中，遇到的情况不可能是非常完美的。比如说：你写的某个模块，用户输入不一定符合你的要求，你的程序要打开某个文件，这个文件可能不存在或者文件格式不对，你要读取数据库的数据，数据可能是空的等。我们的程序在跑着，内存或者硬盘满了，等问题。

- ##### 软件程序在运行过程中，非常可能遇到刚刚提到的这些异常问题，我们叫异常，英文是Exception，意思是例外。这些，例外情况，或者叫异常，怎么让我们写的程序做出合理的处理，而不至于程序崩溃。

- ##### 异常指程序运行中出现的不期而至的各种状况：如文件找不到、网络连接失败、非法参数等。

- ##### 异常发生在程序运行期间，它影响了正常的程序执行流程。

### 简单分类

#### 要理解Java异常处理是如何工作的，需要掌握下列三种类型的异常：

- ##### 检查性异常：最具有代表的检查性异常是用户错误或问题引起的异常，这是程序员无法预见的。例如要打开一个不存在文件时，一个异常就发生了，这些异常在编译时不能被简单地忽略。

- ##### 运行时异常: 运行时异常是可能被程序员避免的异常。与检查性异常相反，运行时异常可以在编译时被忽略。

- ##### 错误ERROR：错误不是异常，而是脱离程序员控制的问题，错误在代码中通常被忽略。例如当栈溢出时，一个错误就发生了，它们在编译也检查不到的。

### 异常体系结构

- ##### Java把异常当作对象来处理，并定义一个基类java.lang.Throwable作为所有异常的超类(祖宗类)。

- ##### 在Java API中已经定义了许多异常类，这些异常类分为两大类，错误Error和异常Exception。

  ![异常的所有分类](https://img-blog.csdnimg.cn/20210601200510879.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQzMjM2MDI2,size_16,color_FFFFFF,t_70#pic_center)

### Error

- ##### Error类对象由Java虚拟机生成并抛出，大多数错误与代码编写者所执行的操作无关。

- ##### Java虚拟机运行错误(Virtual MachineError) ，当Jvm不在有继续执行操作所需的内存资源时，将出现OutOfMemoryError。这些异常发生时，Java虚拟机(JVM) 一般会选择线程终止：

- ##### 还有发生在虚拟机试图执行应用时，如类定义错误(NoClassDefFoundError)、链接错误(LinkageError)，这些错误是不可查的，因为它们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的状况。

### Exception

#### 	分为两种：运行时异常，非运行时异常

- #### 在Exception分支中有一个重要的子类RuntimeException(运行时异常)
  
  - ##### ArraylndexOutOfBoundsException(数组下标越界)
  
  - ##### NullPointerException(空指针异常)
  
  - ##### ArithmeticException(算术异常)
  
  - ##### MissingResourceExoception(丢失资源)
  
  - ##### ClassNotFoundException(找不到类)等异常，这些异常时不检查异常，程序中可以选择捕获处理，也可以不处理。
  
  - ##### 这些异常一般是又程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生；
  
  - ##### Error和Exception的区别：
  
    - ###### Error通常是灾难性的致命错误，是程序无法控制和处理的，当出现这些异常时，Java虚拟机，(jvm)一般会选择终止线程；
  
    - ###### Exception通常情况下是可以被程序处理的，而且在程序中应该尽可能的去处理这些异常。

### 异常处理机制

- #### 抛出异常

- #### 捕获异常

- #### 异常处理的五个关键字

  - ##### try、catch、finally、throw、throws

##### try ( 监控区域 )尝试着去处理某些异常

##### catch 用来捕获异常

##### finally 无论异常执不执行都会走的代码块

##### throw 抛出异常

##### throws 从方法上抛出异常

#### 异常捕获

```java
package oop.demo01;

public class Demo04 {
    public static void main(String[] args) {
            int a = 1;
            int b =0 ;
        try{//监控区域
            System.out.println(a/b);
        }catch (ArithmeticException e){//捕获异常
            System.out.println("程序出现异常，变量B不能为零");
        }finally {//处理善后工作
            System.out.println("finally");
        }
        //finally 可以不要， 一般使用时 在关闭 io流 资源关闭时使用、
    }
}

```

#### 捕获多个异常

```java
package oop.demo01;

public class Demo04 {
    public static void main(String[] args) {
            int a = 1;
            int b =0 ;
            // 假设要捕获多个异常： 从小到大 去捕获。
        try{//监控区域
           // new Demo04().a();
            System.out.println(a/b);
        }catch (Error e){//捕获异常 catch（想要捕获的异常类型）
            System.out.println("程序出现异常，变量B不能为零");
        }catch (Exception e){
            System.out.println("Exception");
        }catch (Throwable e){
            System.out.println("Throwable");
        }
        finally {//处理善后工作
            System.out.println("finally");
        }
        //finally 可以不要， 一般使用时 在关闭 io流 资源关闭时使用、
    }

    public void a (){
        b();
    }
    public void b (){
        a();
    }
}
```

##### 快捷方式,选择要捕获的语句 Ctrl + ALT +t

```java
     try {
            System.out.println(a/b);
        } catch (Exception e) {
            e.printStackTrace();//打印错误栈信息
        } finally {
        }
```

#### 判断抛出异常

```java
package oop.demo01;

public class Demo04 {
    public static void main(String[] args) {
            int a = 1;
            int b =0 ;
            // 假设要捕获多个异常： 从小到大 去捕获。
        try{//监控区域
           // new Demo04().a();

            if (b==0){//主动抛出异常 throw throws
                throw new Exception();//主动抛出异常
            }
            System.out.println(a/b);
        }catch (Error e){//捕获异常 catch（想要捕获的异常类型）
            System.out.println("程序出现异常，变量B不能为零");
        }catch (Exception e){
            System.out.println("Exception");
        }catch (Throwable e){
            System.out.println("Throwable");
        }
        finally {//处理善后工作
            System.out.println("finally");
        }
        //finally 可以不要， 一般使用时 在关闭 io流 资源关闭时使用、
    }


    public void a (){
        b();
    }
    public void b (){
        a();

    }
}

```

#### 在方法中抛出异常

```java
public class Demo04 {
    public static void main(String[] args) {
            int a = 1;
            int b =0 ;
        try {
            new Demo04().test(1,0);
        } catch (ArithmeticException e) {
            e.printStackTrace();
        } finally {
        }
    }

//假设在方法中处理不了这个异常，那么我们就在方法上抛出异常
 public void test(int a , int b) throws ArithmeticException{
      if (b==0){//主动抛出异常 throw throws
         throw new ArithmeticException();//主动抛出异常,一般在方法中使用
         }
     System.out.println(a/b);
 }
}
```

 
